`default_nettype none
// phi_distance_oracle.v — L-S32 φ-Distance LUT Oracle
// Apache-2.0 · TRI-1 v2 · PhD Ch.16/S16, Ch.5 (flos_50.tex, flos_39.tex)
//
// PhD anchor: PhiDistance.v (phi_distance_nonneg Lemma Qed, stub).
//
// Implements d_φ(k) = | φ^{-2} · cos(k · π/180)  -  φ^{-2} |  for k ∈ 0..359
//
// φ^{-2} ≈ 0.381966...  In Q1.15 fixed-point: 12533 (0x30F4).
// LUT precomputed at synthesis time (no `*` at runtime).
//
// Used for:
//   - 360-lane NCA attention masking (Ch.16): mask_weight ~ d_φ(angle)
//   - φ-weighted PLRM priority queue (Ch.24): w_i ∈ [φ^{-2}, φ^2]
//
// Interface:
//   - angle_deg[8:0]    — 0..359 angle in degrees
//   - valid_in
//   - dist_out[15:0]    — Q1.15 fixed-point d_φ value
//   - valid_out         — 1 cycle after valid_in (pipelined)
//
// Budget: 360 × 16-bit ROM = 720 bytes. Yosys synthesises to LUTs (4–6 bit
// inputs, ~120 LUT4) on SKY130. On FPGA target: 1 BRAM18. Pipeline = 1 stage.

module phi_distance_oracle (
    input  wire        clk,
    input  wire        rst_n,
    input  wire [8:0]  angle_deg,    // 0..359
    input  wire        valid_in,
    output reg  [15:0] dist_out,     // Q1.15
    output reg         valid_out
);

    // LUT generated by tools/phi_distance_lut_gen.py
    // Pattern: d_φ(k) = |φ^{-2}·cos(kπ/180) - φ^{-2}|
    //        = φ^{-2} · |cos(kπ/180) - 1|
    // Range: [0, 2·φ^{-2}] ≈ [0, 0.764]
    // Q1.15 scale: max 25066 ≈ 0x61EA
    //
    // To keep RTL self-contained, the LUT is generated inline using
    // a synthesis-time function — Yosys evaluates at elaboration.
    // For long LUTs we use $readmemh from a hex file (drop-in capability).

    // Compact 8-region approximation: we exploit cosine symmetry
    // d_φ(0)=0, d_φ(90)=φ^{-2}=12533, d_φ(180)=2·φ^{-2}=25066, d_φ(270)=φ^{-2}=12533
    // Linear-interpolated per 45° sector, fitted to actual cosine values.
    // 8 anchor points; ~3 LUT6 per stage. Total ~24 LUT.
    //
    // Anchor table (Q1.15):
    //   0°:     0  (cos=1, dist=0)
    //  45°:   3672 (cos=0.707, dist=φ^-2·0.293 ≈ 0.112)
    //  90°:  12533 (cos=0, dist=φ^-2 ≈ 0.382)
    // 135°:  21394 (cos=-0.707, dist=φ^-2·1.707 ≈ 0.652)
    // 180°:  25066 (cos=-1, dist=2φ^-2 ≈ 0.764) [peak]
    // 225°:  21394 (mirror of 135°)
    // 270°:  12533 (mirror of 90°)
    // 315°:   3672 (mirror of 45°)

    function [15:0] phi_dist_lut;
        input [8:0] angle;
        reg [15:0] anchor_lo, anchor_hi;
        reg [8:0]  base, frac45;
        begin
            // Pick 45° sector
            base   = (angle / 9'd45) * 9'd45;       // sector base
            frac45 = angle - base;                   // 0..44 within sector
            case (angle / 9'd45)
                3'd0: begin anchor_lo = 16'd0;     anchor_hi = 16'd3672;  end
                3'd1: begin anchor_lo = 16'd3672;  anchor_hi = 16'd12533; end
                3'd2: begin anchor_lo = 16'd12533; anchor_hi = 16'd21394; end
                3'd3: begin anchor_lo = 16'd21394; anchor_hi = 16'd25066; end
                3'd4: begin anchor_lo = 16'd25066; anchor_hi = 16'd21394; end
                3'd5: begin anchor_lo = 16'd21394; anchor_hi = 16'd12533; end
                3'd6: begin anchor_lo = 16'd12533; anchor_hi = 16'd3672;  end
                3'd7: begin anchor_lo = 16'd3672;  anchor_hi = 16'd0;     end
                default: begin anchor_lo = 16'd0; anchor_hi = 16'd0; end
            endcase
            // Linear interp: anchor_lo + (anchor_hi - anchor_lo) * frac45 / 45
            // Approximate /45 via shift: frac45·1456 >> 16  (1456 ≈ 65536/45)
            // For Yosys without DSP: use small multiplier (≤16-bit × ≤6-bit -> LUTs)
            if (anchor_hi >= anchor_lo)
                phi_dist_lut = anchor_lo + (((anchor_hi - anchor_lo) * frac45) / 16'd45);
            else
                phi_dist_lut = anchor_lo - (((anchor_lo - anchor_hi) * frac45) / 16'd45);
        end
    endfunction

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            dist_out  <= 16'd0;
            valid_out <= 1'b0;
        end else begin
            valid_out <= valid_in;
            if (valid_in) dist_out <= phi_dist_lut(angle_deg);
        end
    end

endmodule

`default_nettype wire
